### ISSUE TITLE
Private Auth API isn't authenticated

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#285]
Ironically.

Right now we're relying on the firewall, we should check user credentials too.

**Comment by AlexGilleran** [comment]
There are examples of authenticated apis in other node services - it should be pretty easy to use the middleware in typescript-common to make this happen.

**Comment by t83714** [comment]
Hi Alex, 

When you got a chance, could you please have a look if this commit does what we want?
b3c044f8d39aaf7318770ffb9f035fb99c23cf8c
Instead of re-using the `mustBeAdmin` middleware,  a little bit different implementation has been included.
In the meantime, I have more play and run some tests on this.

Regards,
Jacky
