### ISSUE TITLE
As a previous user, I can see my recent searches

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#515]
Designs: https://invis.io/CVG233EKXF7#/281956522_04_01_Homepage_saved_search

Icon: [clock.svg.zip](https://github.com/TerriaJS/magda/files/1801534/clock.svg.zip)

Updated 13th Mar 2018: this issue is only about implementing the recent search function on the current design. A separate issue (#554 )has been created for required adjustments to make it match the new homepage design.

**Comment by t83714** [comment]
@tkeuneman here is some clarification regarding its functionality:
- The Recent Searches dropdown will be shown to the user when the search input box is in focus and there is at least one item available for display
- The system will save up to 50 recent search items (keywords & filters) locally (i.e. on user's computer)
- When user input empty string or didn't input any search keyword, the recent searches dropdown will show the last 10 search items
- Otherwise, all local saved search items will be filtered using current user input before shown in the dropdown

Let me know if you have a different opinion on this. Will prepare a demo site for you on this as well.

**Comment by tkeuneman** [comment]
@t83714 a variation on one of them: 

- The system will save up to **5** recent search items (keywords & filters) locally (i.e. on user's computer), from most recent, to least

**Comment by t83714** [comment]
@tkeuneman has updated to 5 recent items & removed the filter function

**Comment by tkeuneman** [comment]
QA: When I'm running an initial search, I see it as a recent search, which doesn't make much sense. Show my search in recent searches on the second, third etc time that I visit the site.

![screen shot 2018-03-27 at 9 52 49 am](https://user-images.githubusercontent.com/2201814/37937356-0e9c2ab0-31a5-11e8-924e-5c51a9ee57f2.png)
