### ISSUE TITLE
Ability to change background image on homepage

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#561]

**Comment by AlexGilleran** [comment]
@tkeuneman can you flesh this out a bit?

I guess it's just a bunch of hard-coded picture/dataset combinations that are picked at random?

**Comment by tkeuneman** [comment]
For sure @AlexGilleran, or it can rotate once a day etc

**Comment by AlexGilleran** [comment]
Put config on S3 with multiple images.

Pick one with a random number.

**Comment by AlexGilleran** [comment]
Will need images.

**Comment by AlexGilleran** [comment]
@maxious to provide datasets for images.
@chloeleichen or @t83714 to implement

**Comment by maxious** [comment]
I'd suggest for the pool image, Explore Sea Level Data https://search.data.gov.au/search?q=Sea%20level

You get WMS and CSV resources although the WMS isn't the right link so it doesn't work.

**Comment by AlexGilleran** [comment]
Appears to have no way to associate images with different lozenge values and causes a white background to come up intermittently, reverting in #706

**Comment by chloeleichen** [comment]
1. We could hardcode lozenge into the config file as well. Is that the plan?
2. re "white background", when you resize the page, it will have to download a new image, causing a flash of white background. This is less likely to be an issue since you don't really resize screen frequently unless you are doing testing

**Comment by t83714** [comment]
@chloeleichen
I think the problem is the previous random function will sometimes produce an invalid index that stops any images being loaded.

If this area will subject to frequent changes, maybe another option is to implement the image / lozenge changing function in the config file (as it's a js file).
Benefits are:
- The config file structure/format will always remain the same
- No need to change web client's code. Therefore, we only need to deploy one thing (config file) when rollout --- minimize the chance of the mismatch between the program and config file.
e.g. the config file could be:
```
window.magda_client_homepage_config = {
    baseUrl:
        "https://s3-ap-southeast-2.amazonaws.com/data-gov-au-frontpage/development/",
    backgroundImageUrls: [
        "twenty-1440w.jpg",
        "twenty-720w.jpg",
        "twenty-0w.jpg",
        "twenty-1080w.jpg",
        "twenty-2160w.jpg",
        "twenty-2880w.jpg"
    ],
    tagLineTextDesktop: "An easy way to find, access and reuse public data",
    tagLineTextMobile: "Find, share, and reuse open government data",
    Lozenge: {
        icon: "camara.svg",
        text: "Explore QLD road data",
        url: "/search?q=Queensland%20road%20data"
    },
    stories: [
        "story1.md",
        "story2.md",
        "story3.md",
        "story4.md",
        "story5.md",
        "story6.md"
    ]
};
(function(){
    var backgroundImgs=[
        [
            "twenty-1440w.jpg",
            "twenty-720w.jpg",
            "twenty-0w.jpg",
            "twenty-1080w.jpg",
            "twenty-2160w.jpg",
            "twenty-2880w.jpg"
        ],
        [
            "pool-1440w.jpg",
            "pool-1080w.jpg",
            "pool-720w.jpg",
            "pool-0w.jpg"
        ]
    ];
    var lozenges = [
        {
            icon: "camara.svg",
            text: "Explore QLD road data",
            url: "/search?q=Queensland%20road%20data"
        },
        {
            icon: "camara.svg",
            text: "Explore Sea level data",
            url: "/search?q=Sea%20level"
        }
    ];

    var idx = (new Date()).getDate()%2; //--- image keep same for the day
    if(backgroundImgs[idx]) window.magda_client_homepage_config.backgroundImageUrls = backgroundImgs[idx];
    if(lozenges[idx]) window.magda_client_homepage_config.Lozenge = lozenges[idx];
})();
```

**Comment by chloeleichen** [comment]
implemented Jacky's code on homepage-config on aws. No PR for this one.
