### ISSUE TITLE
Search results: Change data quality text to 'open data quality'

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#646]

**Comment by adamzerella** [comment]
@tkeuneman Is this what you meant Tash? #752

**Comment by tkeuneman** [comment]
Yup!  Let me know when you want me to QA, or you can share a screenshot of the search results and data pages.

**Comment by adamzerella** [comment]
`Search Results:`
![screenshot from 2018-04-05 13-09-42](https://user-images.githubusercontent.com/1501560/38345467-b3d5aac2-38d2-11e8-8c73-937173b061ae.png)

![screenshot from 2018-04-05 13-09-30](https://user-images.githubusercontent.com/1501560/38345471-b87957fe-38d2-11e8-91c5-ce7d1c402872.png)


</br></br>

`Preview Results:`
![screenshot from 2018-04-05 13-08-17](https://user-images.githubusercontent.com/1501560/38345458-aafa3bfc-38d2-11e8-93a6-90e7cc85324f.png)

![screenshot from 2018-04-05 13-08-30](https://user-images.githubusercontent.com/1501560/38345462-af158b38-38d2-11e8-803c-04e0e64739c5.png)

I didn't modify the Preview Results because I wasn't sure but if it looks better I'll change it?

**Comment by tkeuneman** [comment]
@AlexGilleran Did you want to include the change to the ⭐️system on the search results page for this issue or another one?
