### ISSUE TITLE
"This dataset is already shown" in Terria for many dataset pages

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#652]
E.g. https://search.data.gov.au/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4/details

**Comment by t83714** [comment]
Similar issue: #482
Had a quick look previously. The error was thrown out at this [line](https://github.com/TerriaJS/terriajs/blob/ca9071ac5b496af9cc7990fde74eb7e3b6fefdae/lib/Models/TableCatalogItem.js#L889)
It seems the cause is the `_show` & `_hide` were not called in pairs (with the correct sequence) during `re-enable` and `re-show` process.
Haven't found the root cause of it. 
But one quick fix could be: 
avoid throwing an exception --- just return instead like [here](https://github.com/TerriaJS/terriajs/blob/ca9071ac5b496af9cc7990fde74eb7e3b6fefdae/lib/Models/DataSourceCatalogItem.js#L53)
Another observation is this problem seems only happens to the customized catalog item that returns a new catalog item (e.g. MagdaCatalogItem returns a new CatalogItem for the actual data loading & rendering) --- could be a timing issue as well.
Will run more tests before making any recommendations on this.

**Comment by kring** [comment]
@t83714 I think your suggestion of returning instead of throwing is probably a reasonable solution, but also agree digging a little deeper first makes sense. Let me know if you want me to take a look at it.

**Comment by t83714** [comment]
@kring Thank you! It would be good if you could help to have a look and point out a direction 😄

**Comment by kring** [comment]
Ok, no problem. Can it be reproduced with a simple init file loaded via URL, or does it only happen in the context of Magda?

**Comment by kring** [comment]
Nevermind, I see it it's easy to reproduce with the "Open in NationalMap" link.  I'll take a look.

**Comment by t83714** [comment]
@kring I think it only reproducible within the embedded preview iframe (as that iframe load data via MagdaCatalogItem)
The "Open in NationalMap" link seems work fine for me (I guess because it doesn't go through the `MagdaCatalogItem` )

**Comment by kring** [comment]
Oh really? For me, the map on this page works fine:
https://search.data.gov.au/dataset/ds-dga-fa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4/details

But when I click "Open in NationalMap" I see the error.  I guess if it's timing related it could be different on different systems.

Our of curiosity, why does "Open in NationalMap" not use `MagdaCatalogItem`?

**Comment by t83714** [comment]
Sorry~ I think the issue happened to you could be a different one:
https://github.com/TerriaJS/magda/pull/657
The PR was just created and the production site still has the issue.
Changed the URL to [this](https://nationalmap.gov.au/#start=%7B%22initSources%22%3A%5B%7B%22catalog%22%3A%5B%7B%22name%22%3A%22Credit%20Licence%20Dataset%20-%20National%20Map%22%2C%22type%22%3A%22csv%22%2C%22url%22%3A%22https%3A%2F%2Fdata.gov.au%2Fdataset%2Ffa0b0d71-b8b8-4af8-bc59-0b000ce0d5e4%2Fresource%2F548075a1-c36e-4837-bf26-cc00567b5c23%2Fdownload%2Fcreditlic201803.csv-geo-au%22%2C%22isEnabled%22%3Atrue%2C%22zoomOnEnable%22%3Atrue%7D%5D%7D%5D%7D) will work fine
I thought `MagdaCatalogItem` is a customised catalogItem class not available on national map site?

**Comment by kring** [comment]
You're right, I was seeing #657. In that case I don't seem to be able to reproduce this issue. 😬 

re: MagdaCatalogItem, you're right, it is only in Magda currently, but there's no reason we can't include it in the official TerriaJS release like we do with CkanCatalogItem.

**Comment by t83714** [comment]
No problem. Will have a try on using `postMessage` on `Open in National Map` button and come back to this issue later~

**Comment by t83714** [comment]
Seems a timing related issue and `MagdaCatalogItem` seems not the cause --- this issue can be reproduced on the national map as well. Cannot always reproduce but likely happen if send data via postMessage. See screenshot:
![image](https://user-images.githubusercontent.com/674387/37887891-1953b6de-3110-11e8-82a1-eefb2b6f701a.png)

**Comment by t83714** [comment]
Created a PR in TerriaJS for this:
https://github.com/TerriaJS/terriajs/pull/2921
