### ISSUE TITLE
Write content for the homepage

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#711]

**Comment by tkeuneman** [comment]
@M-BG Could you let me know the exact URLs where you'd like these to go to:
1. Open data toolkit: https://toolkit.data.gov.au/index.php?title=Main_Page
2. Public data: As far as I can tell, there is no submit use case form (see: https://data.gov.au/showcase) Note: @maxious the submit use case email address on this page is out of date
3. ???

**Comment by M-BG** [comment]
Copy for the 'about' page for you (http://magda-dev.terria.io/page/about)

**Data.gov.au** is a product of the Government’s Declaration of Open Government. It is a place anybody can access data published by the Australian Government and public institutions.

Most of the data available is free of charge and can be visualised using the in-built mapping tools.
Individuals and organisations are encouraged to use the data on this site for research, study or applications that add value to the global community.

In addition to open datasets, data.gov.au now includes information about unpublished data and data available for purchase.

Geospatial datasets on data.gov.au and from other spatial indexes are now available through the National Map.

_**How do I share?**_ If you’re an Australian Government entity or private business that provides services to the community, you can register and create an account to share your data sets.
Before you begin, do a quick search of existing organisations to see if your own agency is already listed. If they are, the listed contact can help you to log in and publish your data sets. If not, you can register for the first time.

**Registering for the first time?** We need some basic information to create an account. This includes a username, contact name, and email address.

1. Enter this information to create your account.
2. You will be redirected to your profile page. To set up your profile, select 'Manage'.
3. It is important you fill out your profile completely, including your agency’s logo as your account image. We recommend you use a group inbox for your organisations contact email. This way users can contact the right area or team if they have questions, rather than contacting a specific person. This future-proofs your account for when data stewards are on leave or move organisations. If you choose to include a contact phone number, we recommend a shared or switchboard number for the same reasons.

**Publishing for the first time?** Many agencies are excited but nervous the first time their share data. You should always consider privacy and cleanliness of data before sharing. Information regarding privacy can be found in our Privacy Policy (footer link) and in our Open Data Toolkit (footer link) under ‘publishing your data’. Our Open Data Toolkit also includes useful information and links to other open data sources, on topics like how to form a policy about sharing data through to creating a basic data set.

**Want to keep in touch?**
Subscribe to the new datasets feed or customise a feed below:
Groups - http://data.gov.au/feeds/group/
Tags - http://data.gov.au/feeds/tag/
Search - http://data.gov.au/feeds/custom.atom?q=

**More Information**
Visit the Open Data Toolkit for more information about how to use data.gov.au and related policies and initiatives.

**Comment by M-BG** [comment]
Copy for the 'about' page (http://magda-dev.terria.io/page/about)

**Data.gov.au** is a product of the Government’s Declaration of Open Government. It is a place anybody can access data published by the Australian Government and public institutions.

Most of the data available is free of charge and can be visualised using the in-built mapping tools.
Individuals and organisations are encouraged to use the data on this site for research, study or applications that add value to the global community.

In addition to open datasets, data.gov.au now includes information about unpublished data and data available for purchase.

Geospatial datasets on data.gov.au and from other spatial indexes are now available through the National Map.

**How do I share?** If you’re an Australian Government entity or private business that provides services to the community, you can register and create an account to share your data sets.
Before you begin, do a quick search of existing organisations to see if your own agency is already listed. If they are, the listed contact can help you to log in and publish your data sets. If not, you can register for the first time.

**Registering for the first time?** We need some basic information to create an account. This includes a username, contact name, and email address.

1. Enter this information to create your account.
2. You will be redirected to your profile page. To set up your profile, select 'Manage'.
3. It is important you fill out your profile completely, including your agency’s logo as your account image. We recommend you use a group inbox for your organisations contact email. This way users can contact the right area or team if they have questions, rather than contacting a specific person. This future-proofs your account for when data stewards are on leave or move organisations. If you choose to include a contact phone number, we recommend a shared or switchboard number for the same reasons.

**Publishing for the first time?** Many agencies are excited but nervous the first time their share data. You should always consider privacy and cleanliness of data before sharing. Information regarding privacy can be found in our [Privacy Policy ](https://toolkit.data.gov.au/index.php?title=Publishing_your_data#Privacy_and_security) and in our [Open Data Toolkit](https://toolkit.data.gov.au/index.php?title=Main_Page) under ‘publishing your data’. Our Open Data Toolkit also includes useful information and links to other open data sources, on topics like how to form a [policy](https://toolkit.data.gov.au/index.php?title=Policy) about sharing data through to creating a basic data set.

**Want to keep in touch?**
Subscribe to the new datasets feed or customise a feed below:
Groups - http://data.gov.au/feeds/group/
Tags - http://data.gov.au/feeds/tag/
Search - http://data.gov.au/feeds/custom.atom?q=

**More Information**
Visit the Open Data Toolkit for more information about how to use data.gov.au and related policies and initiatives.

**Comment by M-BG** [comment]
As to your above query Tash:

1. Have added direct link instruction
2. There is ability to submit a use case, but only if you have an account and are logged in;
![image](https://user-images.githubusercontent.com/37681628/38398565-fad1900c-3987-11e8-9813-af64be0f00e2.png)
If you aren't logged in, it only allows you to read other peoples use cases; https://data.gov.au/showcase

**Comment by M-BG** [comment]
Above query (part 2):

3. Cannot find - have asked Alex for help
4. Have updated births to connect to the relevant data sets

**Comment by M-BG** [comment]
Suggestions for changes to http://magda-dev.terria.io/page/dataset-quality copy:
This reduces it by a reading level and just replaces some of the big fancy words with simpler ones to match the tone.

**Dataset Quality** 
How we measure data quality (no caps)
We calculate data quality based on open data best practices, including Tim Berners-Lee's open data scale. This scale is specific enough to be useful but vague enough to be future-proof. It's adopted by many open data portals around the world.

For each of the following points, we add 20% to the data quality rating. These work like building blocks. For a data set to earn 4 stars, it has to meet the first four steps.

1. Is the data available on the web in any format with an open license?
2. Is it available as structured, machine-readable data? For example, an excel file instead of an image scan of the same table.
3. Is it available in a non-proprietary format? Such as CSV instead of Excel.
4. Does the data have URIs to mark things. so that people can reference your stuff?
5. Do you link your data to other data, or provide information on how the data was collected to provide context?

We will continue to update the data quality rating as research continues. If you have any feedback get in touch, or if you're passionate about data quality, get involved in the Australian Government Linked Data Working Group.

**Comment by tkeuneman** [comment]
Thanks @M-BG, I've created individual tickets for each task. 

Re [this comment](https://github.com/TerriaJS/magda/issues/711#issuecomment-379117872), MAGDA currently doesn't allow for use case creation. Is there interim steps that @maxious could take on the CKAN site?

I've created a ticket for this: https://github.com/TerriaJS/magda/issues/775
