### ISSUE TITLE
If data is in an accessURL it's impossible to actually get to it

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#748]
So take [this](https://search.data.gov.au/dataset/ds-aodn-665c701d-0737-4093-8ba0-93765fc12c94/distribution/dist-aodn-665c701d-0737-4093-8ba0-93765fc12c94-0/details?q=dna) for instance

It's got all its data as accessUrls, which is bad, but because we don't have any way at all to surface that to the user, the data is completely unusable.

I literally had to intercept the AJAX request in order to get to the data itself.

This is a pretty massive deal.

**Comment by t83714** [comment]
Do we have an example link to reproduce this problem?

**Comment by AlexGilleran** [comment]
Haha "this" was supposed to be a link, not sure what happened there

**Comment by AlexGilleran** [comment]
https://search.data.gov.au/dataset/ds-aodn-665c701d-0737-4093-8ba0-93765fc12c94/distribution/dist-aodn-665c701d-0737-4093-8ba0-93765fc12c94-0/details?q=dna

**Comment by t83714** [comment]
@AlexGilleran For this situation, will it be good enough to simply display `This dataset can be accessed from:  [the actual access url]` on `Download` section of the distribution page?

**Comment by t83714** [comment]
On second thought, a better option could be making the button below (in screenshot) to open the access URL (instead of opening distribution page as there is no too much info available on distribution page anyway) in a new window?

![image](https://user-images.githubusercontent.com/674387/38396244-26ed443c-397a-11e8-8474-9eaf49e7cc95.png)

**Comment by AlexGilleran** [comment]
Yeah just _some_ way to get to the accessUrl
