### ISSUE TITLE
Organisations: Hide descriptions that match the title

### ISSUE THREAD

**Issue by tkeuneman** [TerriaJS/magda#945]
### Problem description
I see a duplicate of a header being applied as a description. That might be because a publisher adds this as a description to go to the next page, or it might be something that we do. Either way, we should stop that from showing up.

### Problem reproduction steps
![screen shot 2018-05-09 at 10 27 30 am](https://user-images.githubusercontent.com/2201814/39789516-ae60eeba-5373-11e8-8622-799f3ee29683.png)

**Comment by t83714** [comment]
It looks they are duplicate records from different sources.
Will try to do a merge before display.
The records with most detailed description will be chosen when doing the merge.
The merge seems no impact on search all datasets for the publisher as we currently search by publisher name rather than id.
